CREATE TABLE "Shippers"(
    "ShipperID" SERIAL NOT NULL,
    "CompanyName" VARCHAR(255) NOT NULL,
    "Phone" VARCHAR(15) NOT NULL,
    "Address" TEXT NOT NULL,
    PRIMARY KEY ("ShipperID")
);
CREATE TABLE "Users"(
    "UserID" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "FullName" VARCHAR(255) NOT NULL,
    "Address" TEXT NOT NULL,
    "Phone" VARCHAR(15) NOT NULL,
    "Email" VARCHAR(255) NOT NULL,
    "RegistrationDate" DATE NOT NULL,
    PRIMARY KEY ("UserID")
);
CREATE TABLE "Categories"(
    "CategoryID" SERIAL NOT NULL,
    "CategoryName" VARCHAR(100) NOT NULL,
    PRIMARY KEY ("CategoryID")
);
CREATE TABLE "Brands"(
    "BrandID" SERIAL NOT NULL,
    "BrandName" VARCHAR(100) NOT NULL,
    "Description" TEXT NOT NULL,
    PRIMARY KEY ("BrandID")
);
CREATE TABLE "Products"(
    "ProductID" SERIAL NOT NULL,
    "ProductName" VARCHAR(255) NOT NULL,
    "Description" TEXT NOT NULL,
    "Price" DECIMAL(8, 2) NOT NULL,
    "QuantityInStock" INTEGER NOT NULL,
    "CategoryID" INTEGER NOT NULL,
    "BrandID" INTEGER NOT NULL,
    PRIMARY KEY ("ProductID"),
    FOREIGN KEY ("CategoryID") REFERENCES "Categories"("CategoryID") ON DELETE CASCADE,
    FOREIGN KEY ("BrandID") REFERENCES "Brands"("BrandID") ON DELETE SET NULL
);
CREATE TABLE "Orders"(
    "OrderID" SERIAL NOT NULL,
    "UserID" BIGINT NOT NULL,
    "OrderDate" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Pending',
    "PaymentMethod" VARCHAR(50) NOT NULL,
    "ShipperID" INTEGER NOT NULL,
    PRIMARY KEY ("OrderID"),
    FOREIGN KEY ("UserID") REFERENCES "Users"("UserID") ON DELETE CASCADE,
    FOREIGN KEY ("ShipperID") REFERENCES "Shippers"("ShipperID") ON DELETE SET NULL
);
CREATE TABLE "Order_Items"(
    "OrderItemID" SERIAL NOT NULL,
    "OrderID" INTEGER NOT NULL,
    "ProductID" INTEGER NOT NULL,
    "Quantity" INTEGER NOT NULL,
    "Price" DECIMAL(8, 2) NOT NULL,
    PRIMARY KEY ("OrderItemID"),
    FOREIGN KEY ("OrderID") REFERENCES "Orders"("OrderID") ON DELETE CASCADE,
    FOREIGN KEY ("ProductID") REFERENCES "Products"("ProductID") ON DELETE CASCADE
);
CREATE TABLE "Payments"(
    "PaymentID" SERIAL NOT NULL,
    "OrderID" INTEGER NOT NULL,
    "PaymentDate" TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
    "Amount" DECIMAL(8, 2) NOT NULL,
    "Status" VARCHAR(50) NOT NULL DEFAULT 'Completed',
    PRIMARY KEY ("PaymentID"),
    FOREIGN KEY ("OrderID") REFERENCES "Orders"("OrderID") ON DELETE CASCADE
);
INSERT INTO "Categories" ("CategoryName")
VALUES
    ('Toys'),
    ('Accessories'),
    ('Food'),
    ('Grooming'),
    ('Health'),
    ('Training'),
    ('Housing');
INSERT INTO "Users" ("FullName", "Address", "Phone", "Email", "RegistrationDate")
VALUES
    ('Alice Johnson', '123 Pet Lane, Citytown', '+1234567890', 'alice.johnson@example.com', '2019-02-15'),
    ('Bob Smith', '456 Animal Ave, Petville', '+9876543210', 'bob.smith@example.com', '2020-05-30'),
    ('Charlie Brown', '789 Furball St, Barktown', '+1122334455', 'charlie.brown@example.com', '2018-08-10'),
    ('Daisy Green', '101 Catnip Dr, Meowcity', '+9988776655', 'daisy.green@example.com', '2021-03-12'),
    ('Edward Black', '202 Fetch Rd, Dogtown', '+1230984567', 'edward.black@example.com', '2022-11-05'),
    ('Fiona White', '303 Bark St, Woofville', '+4563217890', 'fiona.white@example.com', '2023-01-20'),
    ('George Blue', '404 Scratch Blvd, Clawtown', '+7896541230', 'george.blue@example.com', '2017-06-18'),
    ('Hannah Yellow', '505 Purr Path, Catville', '+1239874560', 'hannah.yellow@example.com', '2024-04-01'),
    ('Ivy Orange', '606 Tail Trail, Petland', '+9871236540', 'ivy.orange@example.com', '2019-09-25'),
    ('Jack Red', '707 Paw Way, Furtown', '+6547893210', 'jack.red@example.com', '2020-12-11'),
    ('Kathy Purple', '808 Claw Rd, Petworld', '+3214569870', 'kathy.purple@example.com', '2018-03-15'),
    ('Leo Gray', '909 Meow Ln, Animalcity', '+1472583690', 'leo.gray@example.com', '2021-10-22'),
    ('Mia Violet', '1010 Chew Ave, Dogland', '+9517538520', 'mia.violet@example.com', '2022-07-04'),
    ('Noah Green', '1111 Barking Blvd, Petville', '+8527419630', 'noah.green@example.com', '2023-09-13'),
    ('Olivia Brown', '1212 Purring Rd, Meowtown', '+7539514560', 'olivia.brown@example.com', '2017-11-06'),
    ('Paul Pink', '1313 Fetch Dr, Dogtown', '+6541237890', 'paul.pink@example.com', '2019-01-29'),
    ('Quinn Gold', '1414 Tail St, Petland', '+1236547890', 'quinn.gold@example.com', '2024-06-18'),
    ('Riley Silver', '1515 Pawpath, Furtown', '+7893216540', 'riley.silver@example.com', '2021-05-25'),
    ('Sophia Black', '1616 Chew Blvd, Barkcity', '+8529637410', 'sophia.black@example.com', '2022-08-30'),
    ('Thomas Cyan', '1717 Catnip Ln, Meowland', '+9514567890', 'thomas.cyan@example.com', '2020-03-10');
    ('Uma Teal', '1818 Tail Ave, Dogtown', '+9517896540', 'uma.teal@example.com', '2023-11-25'),
    ('Victor Lime', '1919 Pawpath, Petworld', '+7894561230', 'victor.lime@example.com', '2019-10-05'),
    ('Wendy Gold', '2020 Meow Blvd, Furtown', '+7418529630', 'wendy.gold@example.com', '2018-07-19'),
    ('Xavier Jade', '2121 Scratch Rd, Barkville', '+9632587410', 'xavier.jade@example.com', '2024-01-15'),
    ('Yara Silver', '2222 Purr St, Catville', '+9513574860', 'yara.silver@example.com', '2020-05-03'),
    ('Zach Crimson', '2323 Barking Blvd, Dogland', '+1238524560', 'zach.crimson@example.com', '2019-04-14'),
    ('Abby Copper', '2424 Catnip Dr, Meowcity', '+7413692580', 'abby.copper@example.com', '2022-02-28'),
    ('Ben Hazel', '2525 Chew Blvd, Petland', '+1593578520', 'ben.hazel@example.com', '2023-10-10'),
    ('Cathy Indigo', '2626 Purring Path, Furtown', '+7891234560', 'cathy.indigo@example.com', '2017-12-31'),
    ('Derek Blue', '2727 Meow Ln, Animalcity', '+4569873210', 'derek.blue@example.com', '2021-06-05'),
    ('Elena Mauve', '2828 Tail Rd, Petville', '+9631472580', 'elena.mauve@example.com', '2019-09-22'),
    ('Frank Red', '2929 Pawpath, Barktown', '+3579514560', 'frank.red@example.com', '2022-01-17'),
    ('Grace Mint', '3030 Scratch Blvd, Catland', '+7893214560', 'grace.mint@example.com', '2024-08-11'),
    ('Hector Olive', '3131 Chew Dr, Dogtown', '+8526549510', 'hector.olive@example.com', '2018-03-04'),
    ('Isla Cyan', '3232 Purring Path, Furtown', '+1594863570', 'isla.cyan@example.com', '2020-11-08'),
    ('Jake Navy', '3333 Tail Blvd, Petworld', '+7531594860', 'jake.navy@example.com', '2021-07-26'),
    ('Kelly Orange', '3434 Barking Rd, Dogtown', '+9518526540', 'kelly.orange@example.com', '2017-04-18'),
    ('Liam Purple', '3535 Catnip Dr, Meowtown', '+3574561590', 'liam.purple@example.com', '2019-05-06'),
    ('Mila Green', '3636 Meow Path, Petcity', '+6549513570', 'mila.green@example.com', '2023-02-21'),
    ('Nate Violet', '3737 Purr Blvd, Catland', '+9513571590', 'nate.violet@example.com', '2022-06-14');
INSERT INTO "Brands" ("BrandName", "Description")
VALUES
    ('PetCo', 'Affordable pet products for all kinds of animals.'),
    ('Nature''s Best', 'Natural and organic pet supplies.'),
    ('HappyPaws', 'Innovative and durable pet toys.'),
    ('FurCare', 'Specialized in grooming and pet care products.'),
    ('VetCare', 'Health-focused products for pets.'),
    ('HomeSweetHome', 'High-quality housing and accessories for pets.'),
    ('TrainPro', 'Training aids and behavioral tools for pets.'),
    ('Pawfect', 'Luxury accessories for stylish pets.'),
    ('GreenPaws', 'Eco-friendly pet products made from sustainable materials.'),
    ('ChewyChums', 'Tasty treats and chews for pets of all sizes.'),
    ('ActiveTail', 'Fitness and activity gear for pets.'),
    ('PetZone', 'General pet supplies for everyday needs.'),
    ('ComfortPaws', 'Soft bedding and cushions for pets'' comfort.'),
    ('HealthyPet', 'Supplements and vitamins for healthier pets.'),
    ('FidoFun', 'Interactive toys for dogs and other active pets.'),
    ('PurrfectChoice', 'Products tailored for cats'' unique needs.'),
    ('CritterCare', 'Small animal products for rabbits, hamsters, and more.'),
    ('WildNest', 'Bird cages, food, and accessories.'),
    ('AquaWorld', 'Aquariums and accessories for fish and aquatic pets.'),
    ('ExoticLife', 'Products for reptiles and exotic pets.'),
    ('BuddyBites', 'Premium pet food made with care.');
INSERT INTO "Products" ("ProductName", "Description", "Price", "QuantityInStock", "CategoryID", "BrandID")
VALUES
    ('Chew Toy', 'Durable rubber toy for dogs.', 10.99, 150, 1, 3),
    ('Cat Scratcher', 'Wooden scratching post for cats.', 25.50, 100, 1, 9),
    ('Fetch Ball', 'High-bounce ball for active dogs.', 12.00, 200, 1, 8),
    ('Interactive Puzzle', 'Brain-training toy for pets.', 35.00, 75, 1, 16),
    ('Leash', 'Durable nylon leash for dogs.', 15.99, 250, 2, 1),
    ('Collar', 'Adjustable collar for pets.', 9.50, 300, 2, 6),
    ('Pet Bed', 'Soft and cozy bed for pets.', 45.00, 120, 2, 13),
    ('Dry Dog Food', 'Premium dry food for adult dogs.', 60.00, 500, 3, 21),
    ('Cat Wet Food', 'High-quality wet food for cats.', 30.00, 350, 3, 2),
    ('Small Pet Mix', 'Nutritional mix for small pets.', 20.00, 400, 3, 18),
    ('Shampoo', 'Gentle shampoo for sensitive skin.', 12.99, 180, 4, 4),
    ('Brush', 'Grooming brush for all coat types.', 8.99, 250, 4, 4),
    ('Vitamins', 'Multivitamin supplement for pets.', 25.00, 100, 5, 14),
    ('Tick Repellent', 'Spray to protect pets from ticks.', 18.00, 200, 5, 5),
    ('Training Whistle', 'High-frequency whistle for dogs.', 9.99, 300, 6, 7),
    ('Clicker', 'Training clicker for behavior shaping.', 5.50, 400, 6, 7),
    ('Dog House', 'Weatherproof dog house.', 150.00, 50, 7, 12),
    ('Cat Tower', 'Multi-level cat play tower.', 200.00, 30, 7, 19);
    ('Squeaky Plush Toy', 'Soft plush toy with built-in squeaker for dogs.', 14.99, 120, 1, 15),
    ('Catnip Mouse Toy', 'Mouse-shaped toy infused with catnip.', 8.00, 220, 1, 17),
    ('Rope Tug Toy', 'Durable rope for tug games with dogs.', 11.50, 180, 1, 10),
    ('Laser Pointer', 'Interactive laser toy for cats.', 9.00, 250, 1, 19),
    ('Pet Carrier', 'Portable pet carrier for travel.', 75.00, 90, 2, 12),
    ('Raincoat for Dogs', 'Waterproof coat for rainy walks.', 30.00, 70, 2, 8),
    ('Cooling Mat', 'Cooling mat for hot weather comfort.', 50.00, 60, 2, 13),
    ('Grain-Free Dog Food', 'Healthy grain-free formula.', 70.00, 450, 3, 21),
    ('Freeze-Dried Treats', 'Natural freeze-dried treats for pets.', 25.00, 300, 3, 9),
    ('Dental Chews', 'Chews that help clean pets’ teeth.', 15.50, 200, 3, 3),
    ('Nail Clippers', 'Pet nail clippers for safe trimming.', 10.99, 150, 4, 4),
    ('Ear Cleaner', 'Gentle ear cleaning solution.', 12.50, 200, 4, 14),
    ('Joint Care Supplement', 'Supplement to support healthy joints.', 40.00, 100, 5, 14),
    ('Eye Drops for Pets', 'Moisturizing eye drops for pets.', 18.99, 150, 5, 5),
    ('Agility Tunnel', 'Training tunnel for active dogs.', 120.00, 40, 6, 11),
    ('Target Stick', 'Training tool for behavior shaping.', 15.00, 70, 6, 7),
    ('Bird Cage', 'Spacious cage for birds.', 180.00, 50, 7, 20),
    ('Aquarium Starter Kit', 'Complete kit for aquarium beginners.', 220.00, 20, 7, 18),
    ('Reptile Habitat', 'Fully equipped habitat for reptiles.', 300.00, 10, 7, 22);

INSERT INTO "Shippers" ("CompanyName", "Phone", "Address")
VALUES
    ('FastPet Delivery', '+1234567890', '123 Delivery Lane, PetCity'),
    ('PawExpress', '+9876543210', '456 Speedy Ave, Barktown'),
    ('HappyTail Couriers', '+1122334455', '789 Quick Rd, Meowville'),
    ('FurFly Logistics', '+9988776655', '101 Swift St, Petland');

INSERT INTO "Orders" ("UserID", "OrderDate", "Status", "PaymentMethod", "ShipperID")
VALUES
	(5, '2020-02-15', 'Completed', 'Credit Card', 1),
    (3, '2021-06-11', 'Pending', 'PayPal', 2),
    (8, '2022-08-19', 'Shipped', 'Cash on Delivery', 3),
    (1, '2023-03-29', 'Completed', 'Credit Card', 1),
    (10, '2021-01-10', 'Cancelled', 'PayPal', 4),
    (7, '2019-12-05', 'Completed', 'Credit Card', 3),
    (4, '2022-05-25', 'Shipped', 'Cash on Delivery', 2),
    (15, '2024-07-04', 'Completed', 'Credit Card', 4),
    (18, '2023-09-21', 'Pending', 'PayPal', 1),
    (11, '2020-10-15', 'Cancelled', 'Cash on Delivery', 2),
    (2, '2021-02-28', 'Completed', 'Credit Card', 3),
    (14, '2023-12-12', 'Shipped', 'PayPal', 4),
    (9, '2019-06-14', 'Completed', 'Cash on Delivery', 1),
    (20, '2024-03-05', 'Pending', 'Credit Card', 3),
    (16, '2021-11-22', 'Shipped', 'PayPal', 4),
    (12, '2022-09-13', 'Completed', 'Cash on Delivery', 2),
    (17, '2020-05-18', 'Cancelled', 'Credit Card', 1),
    (6, '2023-06-08', 'Pending', 'PayPal', 3),
    (19, '2024-01-02', 'Completed', 'Credit Card', 2),
    (13, '2022-04-27', 'Shipped', 'Cash on Delivery', 4);
	(12, '2023-07-18', 'Completed', 'Credit Card', 2),
    (3, '2021-11-03', 'Pending', 'PayPal', 1),
    (7, '2022-02-14', 'Cancelled', 'Cash on Delivery', 4),
    (9, '2019-09-26', 'Shipped', 'Credit Card', 3),
    (6, '2024-05-12', 'Completed', 'PayPal', 2),
    (15, '2020-08-22', 'Pending', 'Cash on Delivery', 1),
    (2, '2022-10-01', 'Completed', 'Credit Card', 4),
    (13, '2021-01-19', 'Shipped', 'PayPal', 3),
    (18, '2023-04-30', 'Cancelled', 'Cash on Delivery', 2),
    (10, '2022-12-25', 'Completed', 'Credit Card', 1),
    (4, '2020-03-15', 'Pending', 'Cash on Delivery', 2),
    (14, '2023-09-09', 'Shipped', 'Credit Card', 3),
    (11, '2024-02-18', 'Completed', 'PayPal', 4),
    (5, '2021-06-20', 'Pending', 'Credit Card', 1),
    (17, '2019-11-08', 'Shipped', 'Cash on Delivery', 3),
    (16, '2022-05-04', 'Completed', 'PayPal', 4),
    (19, '2023-01-11', 'Cancelled', 'Credit Card', 2),
    (8, '2020-07-25', 'Shipped', 'Cash on Delivery', 1),
    (20, '2022-09-30', 'Completed', 'PayPal', 4),
    (1, '2023-08-15', 'Pending', 'Credit Card', 2);
    (5, '2025-01-03', 'Completed', 'Credit Card', 1),
    (8, '2025-01-07', 'Pending', 'PayPal', 2),
    (12, '2025-01-10', 'Shipped', 'Cash on Delivery', 3),
    (3, '2025-01-11', 'Completed', 'Credit Card', 4),
    (15, '2025-01-12', 'Cancelled', 'PayPal', 2);
INSERT INTO "Order_Items" ("OrderID", "ProductID", "Quantity", "Price")
VALUES
    (41, 3, 2, 12.00),  -- Order 41, Product 3
    (42, 7, 1, 45.00),  -- Order 42, Product 7
    (43, 12, 3, 12.99), -- Order 43, Product 12
    (44, 15, 5, 25.00), -- Order 44, Product 15
    (45, 8, 2, 30.00),  -- Order 45, Product 8
    (46, 4, 1, 35.00),  -- Order 46, Product 4
    (47, 9, 4, 60.00),  -- Order 47, Product 9
    (48, 2, 3, 10.99),  -- Order 48, Product 2
    (49, 14, 1, 18.00), -- Order 49, Product 14
    (50, 6, 2, 15.99),  -- Order 50, Product 6
    (51, 5, 1, 14.99),  -- Order 51, Product 5
    (52, 10, 2, 25.50), -- Order 52, Product 10
    (53, 1, 3, 75.00),  -- Order 53, Product 1
    (54, 11, 4, 70.00), -- Order 54, Product 11
    (55, 13, 2, 20.00), -- Order 55, Product 13
    (56, 3, 1, 12.00),  -- Order 56, Product 3
    (57, 15, 2, 25.00), -- Order 57, Product 15
    (58, 8, 4, 30.00),  -- Order 58, Product 8
    (59, 4, 3, 35.00),  -- Order 59, Product 4
    (60, 9, 5, 60.00),  -- Order 60, Product 9
    (61, 7, 1, 45.00),  -- Order 61, Product 7
    (62, 12, 3, 12.99), -- Order 62, Product 12
    (63, 14, 2, 18.00), -- Order 63, Product 14
    (64, 10, 4, 25.50), -- Order 64, Product 10
    (65, 6, 2, 15.99),  -- Order 65, Product 6
    (66, 11, 3, 70.00), -- Order 66, Product 11
    (67, 13, 1, 20.00), -- Order 67, Product 13
    (68, 5, 4, 14.99),  -- Order 68, Product 5
    (69, 8, 2, 30.00),  -- Order 69, Product 8
    (70, 3, 1, 12.00),  -- Order 70, Product 3
    (71, 15, 3, 25.00), -- Order 71, Product 15
    (72, 9, 5, 60.00),  -- Order 72, Product 9
    (73, 7, 2, 45.00),  -- Order 73, Product 7
    (74, 14, 3, 18.00), -- Order 74, Product 14
    (75, 1, 2, 75.00),  -- Order 75, Product 1
    (76, 12, 4, 12.99), -- Order 76, Product 12
    (77, 10, 1, 25.50), -- Order 77, Product 10
    (78, 11, 3, 70.00), -- Order 78, Product 11
    (79, 2, 5, 10.99),  -- Order 79, Product 2
    (80, 13, 2, 20.00), -- Order 80, Product 13
    (81, 6, 1, 15.99),  -- Order 81, Product 6
    (82, 5, 4, 14.99),  -- Order 82, Product 5
    (83, 8, 2, 30.00),  -- Order 83, Product 8
    (84, 4, 3, 35.00),  -- Order 84, Product 4
    (85, 9, 5, 60.00);  -- Order 85, Product 9
INSERT INTO "Payments" ("OrderID", "PaymentDate", "Amount", "Status")
VALUES
    (41, '2020-02-15', 24.00, 'Completed'),
    (42, '2020-06-18', 45.00, 'Pending'),
    (43, '2021-01-12', 38.97, 'Completed'),
    (44, '2021-08-08', 125.00, 'Failed'),
    (45, '2022-04-14', 60.00, 'Completed'),
    (46, '2022-09-20', 35.00, 'Pending'),
    (47, '2023-01-18', 240.00, 'Completed'),
    (48, '2023-07-04', 32.97, 'Completed'),
    (49, '2023-11-20', 18.00, 'Failed'),
    (50, '2024-03-10', 31.98, 'Completed'),
    (51, '2024-07-15', 14.99, 'Pending'),
    (52, '2024-10-25', 51.00, 'Completed'),
    (53, '2025-01-01', 225.00, 'Completed'),
    (54, '2025-01-05', 280.00, 'Failed'),
    (55, '2025-01-09', 40.00, 'Completed'),
    (56, '2020-03-02', 24.00, 'Pending'),
    (57, '2021-05-10', 48.50, 'Completed'),
    (58, '2022-06-14', 32.50, 'Failed'),
    (59, '2023-12-12', 75.00, 'Completed'),
    (60, '2024-09-10', 99.99, 'Pending'),
    (61, '2021-04-15', 55.00, 'Completed'),
    (62, '2020-11-25', 29.99, 'Completed'),
    (63, '2022-03-18', 65.00, 'Failed'),
    (64, '2023-06-30', 110.00, 'Completed'),
    (65, '2024-08-12', 85.50, 'Pending'),
    (66, '2024-11-11', 150.00, 'Completed'),
    (67, '2025-01-11', 200.00, 'Completed'),
    (68, '2020-04-21', 12.50, 'Failed'),
    (69, '2021-07-04', 130.00, 'Completed'),
    (70, '2022-09-09', 45.00, 'Pending'),
    (71, '2023-03-29', 78.25, 'Completed'),
    (72, '2024-12-05', 56.75, 'Failed'),
    (73, '2025-01-07', 180.00, 'Completed'),
    (74, '2020-05-17', 23.00, 'Completed'),
    (75, '2021-11-02', 99.99, 'Pending'),
    (76, '2022-07-23', 125.00, 'Completed'),
    (77, '2023-09-15', 65.00, 'Failed'),
    (78, '2024-05-12', 89.00, 'Completed'),
    (79, '2024-06-08', 45.00, 'Pending'),
    (80, '2020-08-30', 35.99, 'Completed'),
    (81, '2021-02-18', 105.00, 'Completed'),
    (82, '2022-12-22', 72.50, 'Failed'),
    (83, '2023-10-19', 140.00, 'Completed'),
    (84, '2024-01-03', 99.00, 'Pending'),
    (85, '2025-01-12', 60.00, 'Completed');